version: "3.9"

services:
  order-service:
    build: ./src/services/order-service
    container_name: order-service
    ports:
      - "5001:5001"
    volumes:
      - ./src/shared:/app/shared # Mount shared folder
      - ./src/scripts/mongodb:/app/scripts/mongodb
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env

  inventory-service:
    build: ./src/services/inventory-service
    container_name: inventory-service
    ports:
      - "5002:5002"
    volumes:
      - ./src/shared:/app/shared # Mount shared folder
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env

  payment-service:
    build: ./src/services/payment-service
    container_name: payment-service
    ports:
      - "5003:5003"
    volumes:
      - ./src/shared:/app/shared # Mount shared folder
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env

  notification-service:
    build: ./src/services/notification-service
    container_name: notification-service
    ports:
      - "5004:5004"
    volumes:
      - ./src/shared:/app/shared # Mount shared folder
    depends_on:
      - kafka
    env_file:
      - .env

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongodb_data:
